const contenuti = {
    introduzione: `<h2>Introduzione</h2><p>Viviamo immersi nella comunicazione digitale, e i meme sembrano farne parte tanto quanto i messaggi vocali o le notifiche dei social. A prima vista sono semplici, quasi banali: immagini ironiche che ci fanno ridere, ci distraggono, ci aiutano a sdrammatizzare. Ma dietro questa apparente leggerezza, si nasconde un linguaggio inaspettatamente ricco: pieno di riferimenti, codici e significati che mutano di continuo. Da qui nasce la domanda: i meme possono essere considerati una forma d’arte? Oppure sono solo contenuti effimeri da scrollare senza pensarci troppo? Questo interrogativo è il cuore della tesi, che prova a esplorare proprio quel territorio incerto e affascinante dove l’arte incontra la comunicazione, e dove il pubblico diventa anche autore. Lo studio si sviluppa in tre capitoli: il primo analizza cosa sono i meme e come si sono evoluti; il secondo riflette sui loro limiti in ambito artistico; il terzo cerca di ribaltare il punto di vista, ipotizzando il valore espressivo e creativo del meme nella cultura contemporanea. Il vero obiettivo non è dare una risposta definitiva, ma interrogarsi, capire, approfondire.</p>`,
    cap1: `<h2>1° Capitolo</h2><p>I meme oggi sono ovunque, ma il loro percorso è tutt’altro che banale. Nascono come concetto nel 1976, quando Richard Dawkins parla di “meme” come unità culturale che si diffonde e si modifica, un po’ come fanno i geni. Con l’arrivo di internet, questo concetto si trasforma in qualcosa di visivo, virale, sintetico. Il capitolo ripercorre le tappe fondamentali: dal graffito "Kilroy Was Here" alla Dancing Baby degli anni ‘90, fino alla cultura delle piattaforme come 4chan e Reddit. I meme non sono solo contenuti divertenti, ma veri e propri strumenti di comunicazione adattivi, capaci di sintetizzare idee complesse in pochi pixel. La loro struttura flessibile – fatta di template riutilizzabili, editing grezzo e font riconoscibili – ne favorisce la diffusione, la personalizzazione e la partecipazione collettiva. Viene analizzata anche la soglia d’attenzione ridotta degli utenti digitali, che li rende il medium perfetto per il nostro tempo. Inoltre, si osserva come i meme abbiano avuto impatti significativi anche in ambito politico e sociale, dimostrando la loro forza comunicativa e la capacità di influenzare il dibattito pubblico.</p>`,
    cap2: `<h2>2° Capitolo</h2><p>In questo capitolo si entra nel vivo del dibattito: i meme possono essere arte oppure no? Valentina Tanni, con il suo saggio Memestetica, propone una visione lucida e disincantata. Secondo lei, il meme non nasce con finalità artistiche, bensì come dispositivo linguistico. È un contenuto veloce, virale, che mira all’immediatezza, non alla contemplazione. L’estetica amatoriale – immagini sgranate, font bizzarri, nonsense – diventa un punto di forza, una cifra stilistica della cultura digitale. Ma se da un lato questa semplicità democratizza la creazione, dall’altro rende difficile parlare di vera arte. Si riflette anche sull’autorialità: nei meme, l’identità dell’autore si dissolve, e conta più il processo collettivo che il gesto singolo. Viene richiamato il pensiero di Roland Barthes sulla “morte dell’autore”, e vengono accostati artisti come Jeff Koons e Barbara Kruger al mondo dei meme per la loro capacità di giocare con la comunicazione visiva popolare. Il meme diventa così uno specchio della nostra epoca: frammentato, iperconnesso, saturo di immagini e paradossi.</p>`,
    cap3: `<h2>3° Capitolo</h2><p>Il terzo capitolo ribalta l’approccio. Se Tanni è critica e scettica, Alessandro Lolli propone una visione più aperta e costruttiva. Per lui, i meme sono espressioni creative che, pur non rientrando nei canoni dell’arte tradizionale, meritano una legittimazione culturale. Il meme è linguaggio, è remix, è appartenenza: come le sottoculture punk o hip hop, anche il mondo dei memer costruisce un’identità attraverso codici condivisi. Viene analizzata l’evoluzione dei meme: da quelli pre-ironici a quelli metaironici, passando per ironia e post-ironia. I dank meme e i brainrot italiani diventano esempi di comicità assurda, grottesca e dissociata, capace di rappresentare l’ansia e il caos della nostra epoca. E così, il meme si avvicina alle pratiche artistiche concettuali, dove ciò che conta non è il contenuto in sé, ma il processo e la riflessione che genera. Il capitolo si chiude con esempi di artisti contemporanei – Eva & Franco Mattes, Petra Cortright, Fontanesi – che incorporano il linguaggio memetico nelle loro opere, dimostrando come i meme possano essere un terreno fertile per una nuova forma d’arte digitale e partecipativa.</p>`,
    conclusione: `<h2>Conclusione</h2><p>In chiusura, la tesi non pretende di dare una definizione univoca, ma piuttosto suggerisce di cambiare prospettiva. Non è tanto rilevante chiedersi se i meme siano arte, quanto quando lo diventano. Alcuni, in certi contesti, riescono a comunicare emozioni, idee e riflessioni come qualsiasi opera d’arte. Il loro valore non sta nella firma, nella tecnica o nell’estetica classica, ma nella loro capacità di creare significato condiviso, di attivare una reazione, di raccontare la realtà attraverso forme nuove. In questo senso, i meme sono una sintesi perfetta della cultura visiva contemporanea: rapidi, partecipativi, ironici, spesso destabilizzanti. Sono il linguaggio con cui parliamo di noi, del nostro tempo, delle nostre contraddizioni.</p>`,
    progetto: `<h2>Progetto Artistico</h2><p>Descrizione del progetto artistico...</p>`
};

function showSection(section) {
    const contentDiv = document.getElementById('textContent');
    contentDiv.innerHTML = contenuti[section] || '<p>Sezione non trovata.</p>';
    contentDiv.scrollTop = 0;
}

document.addEventListener('DOMContentLoaded', () => {
    const items = document.querySelectorAll('.menu-item');
    items.forEach(item => {
        item.addEventListener('click', () => {
            const section = item.getAttribute('data-section');
            showSection(section);
        });
    });
});